### ISSUE TITLE
Read/write sensor support

### ISSUE THREAD

**Issue by takerukoushirou** [olegtarasov/esphome-opentherm#10]
Thank you for the hard work on refining this component into an official ESPHome component!

I was experimenting with what sensors are supported by my heater (which sadly reports zero for many measurements that it certainly internally does) and what values can be set. Setting DHW and maximum CH setpoints is well supported and reflected on the device. I noticed an inconsistency though. When the two number inputs are defined, they show up in HA and can be set, but they initially start with blank inputs. If I instead configure sensors for `t_dhw_set` and `max_t_set`, they show the currently on the heater configured values. Defining both the number inputs and sensors again leads to initially blank inputs but also 0.0 as reported values for both sensors. It seems that when number inputs are configured, reading `t_dhw_set` and `max_t_set` is disabled or fails.
It would be ideal if the number inputs could initially show the values configured on the heater.

Corresponding configuration segments:
```yaml
output:
  - platform: opentherm
    t_set:
      id: opentherm_ch_set_temperature
      min_value: 30
      max_value: 80
      auto_max_value: true
      zero_means_zero: true

number:
  - platform: opentherm
    t_dhw_set:
      name: "Domestic hot water setpoint"
      auto_min_value: true
      auto_max_value: true
    max_t_set:
      name: "Central heating maximum setpoint"
      auto_min_value: true
      auto_max_value: true

# Sensors work when no number input is specified, otherwise read 0.0.
sensor:
  - platform: opentherm
    t_dhw_set:
      name: "Domestic hot water setpoint"
    max_t_set:
      name: "Central heating maximum setpoint"
```

![Screenshot 2024-10-12 at 16 07 07](https://github.com/user-attachments/assets/d5ff2d31-6f3a-4398-b50b-91207982c141)
