### ISSUE TITLE
Report boiler communication problem

### ISSUE THREAD

**Issue by clau-bucur** [olegtarasov/esphome-opentherm#17]
Currently if the component can't talk to the boiler, I see no way that this problem is reported back to the user.
There's the `fault_indication` mentioned in the docs but it's unclear what kind of faults it reports.

Scenarios:
- on ESPHome startup the boiler is unreachable. All OT sensors are set to Unknown including `fault_indication`.
- the component loses communication with the boiler during regular operation. OT sensors state remain unchanged. Maybe their state should change to `Unknown` if the fault persists for a predefined (configurable) period of time.

IMHO the `fault_indication` should be enabled and indicate the fault in these cases.
Or at least another sensor should exist to indicate these communication faults.

**Comment by itzViking** [comment]
Sharing here how I worked around this, as I also wanted to track communication failures.

In your yaml, create a global variable where we store when a sensor was last updated

```
globals:
  - id: last_sensor_update
    type: long
    restore_value: no
    initial_value: '0'
```

Now, attach a lambda to one of the sensors that gets updated on every cycle. I used t_boiler:

```
  - platform: opentherm
    t_boiler:
      name: "Boiler water temperature"
      id: boiler_ch_temp
      on_value:
        then:
          - lambda: |-
              id(last_sensor_update) = millis();  // Store last update time
              ESP_LOGD("sensor", "Boiler sensor updated.");
```

Then create an interval entity that looks at this variable and does/calls something else if it exceeds the timeout

```
interval:
  - interval: 60s
    then:
      - lambda: |-
          if ((millis() - id(last_sensor_update)) > 300000) {  // 5 minutes timeout. Probably works down to a few seconds.
            ESP_LOGW("sensor", "Boiler sensor hasn't updated, rebooting ESP...");  // or some other action that warns you about comms failure
            id(reboot_script).execute();
          }
```

At the end I add a reboot script that "pushes" the software reset button as that works for me to restore comms, but get creative!

```
script:
  - id: reboot_script
    mode: restart
    then:
      - logger.log: "Rebooting ESP due to sensor timeout..."
      - delay: 2s
      - button.press: restart_switch  # Call the software reboot switch
button:
  - platform: restart
    id: restart_switch
    name: "Restart ESP"
```
