### ISSUE TITLE
Protocol error occured while receiving response: type: NO_CHANGE_TOO_LONG

### ISSUE THREAD

**Issue by nyctomanica** [olegtarasov/esphome-opentherm#19]
Hey, thank you so much for developing this!

I've been trying to set up this component recently, using a Wemos D1 Mini esp32, thehognl opentherm shield, and a Viessmann 050-W combi boiler.

However I've been unable to get anything to work so far, with my logs filled with "Protocol error occured while receiving response: type: NO_CHANGE_TOO_LONG" every few ms.
My boiler also shows error A9, meaning Opentherm Error.

I've tried reversing the pins for in/out and simplifying my config file to a very basic level, but the issue persists.

Could you let me know if this is a bug, or user/hardware error (or stupidity :))

My config is below, and I have attached my latest full logs.

Cheers!

```
esphome:
  name: heat-o-matic
  friendly_name: Heat-o-matic

esp32:
  board: wemos_d1_mini32

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: [redacted]

ota:
  - platform: esphome
    password: [redacted]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heat-O-Matic Fallback Hotspot"
    password: [redacted]

captive_portal:

external_components:
  source: github://olegtarasov/esphome-opentherm@main

opentherm:
  in_pin: GPIO19
  out_pin: GPIO18

# Values that can be set maually from HA interface
number:
  - platform: opentherm
    # Hot water temperature
    t_dhw_set:
      id: dhw_setpoint
      name: "Hot water temperature"
      min_value: 30
      max_value: 60
      initial_value: 45
      restore_value: true
  # Heating loop temperature
    t_set:
      id: ch_setpoint
      name: "Heating loop temperature"
      min_value: 35
      max_value: 70
      initial_value: 45
      restore_value: true

switch:
  - platform: opentherm

    ch_enable:
      id: ch_enable
      name: "Central Heating enabled"
      restore_mode: RESTORE_DEFAULT_OFF
    dhw_enable:
      id: dhw_enable
      name: "Hot Water enabled"
      restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: opentherm
    rel_mod_level:
      name: "Relative modulation level"
    ch_pressure:
      name: "Water pressure"
    t_boiler:
      name: "Heating water temperature"
    t_dhw:
      name: "Hot water temperature"
    t_exhaust:
      name: "Exhaust temperature"
    t_ret:
      name: "Return water temperature"
    opentherm_version_device:
      name: "Opentherm version"
    oem_diagnostic_code:
      name: "Boiler diagnostic code"
    oem_fault_code:
      name: "Boiler fault code"

binary_sensor:
  - platform: opentherm
    ch_active:
      name: "Central Heating active"
    dhw_active:
      name: "Hot Water active"
    flame_on:
      name: "Burner on"
    fault_indication:
      name: "Boiler fault"
      entity_category: diagnostic
    diagnostic_indication:
      name: "Diagnostic event"
      entity_category: diagnostic
    service_request:
      name: "Service needed"
      entity_category: diagnostic
```

**Comment by nyctomanica** [comment]
oops, forgot logs
[logs_heat-o-matic_logs.txt](https://github.com/user-attachments/files/17787979/logs_heat-o-matic_logs.txt)

**Comment by FreeBear-nc** [comment]
> I've been trying to set up this component recently, using a Wemos D1 Mini esp32, thehognl opentherm shield, and a Viessmann 050-W combi boiler.
> ```
> opentherm:
>   in_pin: GPIO19
>   out_pin: GPIO18
> ```

Pretty sure GPIO18 & GPIO19 are not routed to pins on the D1-mini. Try:
```
opentherm:
  in_pin: GPIO12 # D6
  out_pin: GPIO14 # D5
```

Ooops. The D1-miniESP32 is a different beast with double row headers on either side. GPIO18 & GPIO19 are on the inner row and occupy the same points as D5 & D6.

**Comment by FreeBear-nc** [comment]
Just ordered one of them D1-mini-ESP32 boards. Should take about a week to arrive from China. Once here, I can check the GPIO assignments.

**Comment by clau-bucur** [comment]
I have the same D1 mini ESP32 board running fine with:
```
opentherm:
  in_pin: GPIO19
  out_pin: GPIO18
  ch_enable: true
  dhw_enable: true
```

I can check later the exact used pins on the board if needed.

**Comment by olegtarasov** [comment]
@nyctomanica Can you post photos of your D1 mini boards from both sides as well as photos of the actual OpenTherm shields you are using? Judging from https://www.wemos.cc/en/latest/d1/d1_mini.html, I tend to agree with @FreeBear-nc: pins 18 and 19 seem to be unrouted. There are many flavors and variations of those Chinese boards, so your version could be different from @clau-bucur's.

**Comment by nyctomanica** [comment]
Aye sure, here you go!
That's a good shout too, I'll try using a different style of ESP32 board (got some AZdelivery ones kicking about somewhere)

Apologies for the messy ribbon cable too, although it does all test out ok with a multimeter :)
Couldn't find any headers at the time, although sod's law dictated that some would turn up 15min afterwards...

![PXL_20241119_141014920](https://github.com/user-attachments/assets/74520ff4-aa62-46ad-a2d3-e9d377c19033)
![PXL_20241119_140941755](https://github.com/user-attachments/assets/376346f7-fa5c-49c2-8a28-b38eb92c69ac)
![PXL_20241119_140936623](https://github.com/user-attachments/assets/5270043b-4ad8-4205-b3a8-c5b048ce8352)
![PXL_20241119_140916426 MP](https://github.com/user-attachments/assets/56a90897-0095-4c5b-bfdf-5f749389292b)
![PXL_20241119_140858478](https://github.com/user-attachments/assets/5fe4c655-0dc1-4624-ac46-f59c4384d6bf)

**Comment by nyctomanica** [comment]
I'm going to have a go with the same-ish config, but a different esp32 board, will report back :)

**Comment by olegtarasov** [comment]
@nyctomanica  It actually looks like the board I use, a variant of MH ET Live Esp32MiniKit. Try changing the board in your config to this:

```yaml
esp32:
  board: mhetesp32minikit
```

**Comment by nyctomanica** [comment]
@olegtarasov will give that a try, thanks!

**Comment by nyctomanica** [comment]
That didn't seem to help, although I do now have some new errors...

NO_TRANSITION, and ERROR_PROTOCOL, as well as the original NO_CHANGE_TOO_LONG

[logs_heat-o-matic_logs.txt](https://github.com/user-attachments/files/17817208/logs_heat-o-matic_logs.txt)

Using @olegtarasov's board type, but same config as before.

I'll give another ESP32 board a go now

**Comment by nyctomanica** [comment]
Tried again with an AZdelivery board (```esp32:
  board: az-delivery-devkit-v4```), but received the same log messages as the last try...
  
Beginning to think it's actually a problem with the boiler or shield, but I don't have others to test it with.
Ordered a DIYLESS shield though, so I'll have one of those to test with soonish :)

![PXL_20241119_154544555 MP - Copy](https://github.com/user-attachments/assets/cdaf4a51-5779-4360-9591-3259436b86aa)
[logs_heat-o-matic_logs(1).txt](https://github.com/user-attachments/files/17817801/logs_heat-o-matic_logs.1.txt)

**Comment by nyctomanica** [comment]
Interestingly Tasmota's Opentherm module doesn't seem to work with either board, so I'm leaning towards a shield/boiler issue...

**Comment by nyctomanica** [comment]
I've verified that the pins are assigned correctly (on the Wemos clone board) in ESPhome by connecting the shield's DS18B20 sensor to both GPIO18 and 19, both times reading temperature from the sensor worked as expected. 
Using these pins to control LEDs worked as well, so that board seems to be good.

Also tried the DIYLESS ESP32 wifi thermostat sketch as it uses a different Opentherm library, but still no communication back from the boiler. 
Interestingly enabling CH from this worked somewhat, the boiler started to heat but no values showed in its webUI.

So I'm thinking that the Opentherm shield has an issue, not the software! 
A new DIYLESS one is on the way though, so I'll test that once it arrives.

**Comment by FreeBear-nc** [comment]
>  A new DIYLESS one is on the way though, so I'll test that once it arrives.

You get a bright green blinky LED to confirm the communication is working. Personally, I find the LED a bit too bright...

P.S. If you are in the UK, I could hook your board up and check the signals out with a scope.

**Comment by nyctomanica** [comment]
@FreeBear-nc quick question, which version of the Vitodens 050-W do you have? Is it the one with the white front panel (BPJC)?

I've received a new thehognl shield (thought I'd give a new one a go in case it was broken, still waiting for the DIYLESS), but I still have no communication at all with the boiler with the same log messages.

Makes me think that the boiler either isn't OpenTherm compatible, or has some hidden setup menu to enable it which I can't find details about...

Also asked Viessmann about how to connect an OpenTherm stat, but they just told me to do exactly what I've been doing (terminals 1+2 underneath)!

So until the DIYLESS shield (and their ESP32, I ordered the combo ESP+shield thermostat) arrives, I'm at a loss!

**Comment by FreeBear-nc** [comment]
> @FreeBear-nc quick question, which version of the Vitodens 050-W do you have? Is it the one with the white front panel (BPJC)?
> Also asked Viessmann about how to connect an OpenTherm stat, but they just told me to do exactly what I've been doing (terminals 1+2 underneath)!

Have a BOKA which is the current version of the 050 (installed last year). Your comment about the connection terminals reminded me that I did have  problem initially with any OpenTherm thermostat not working - The ruddy terminals were wired up the wrong way round (the installer also failed to enable OT mode in the menu, but that is a different beef). Traced the wiring from the boiler motherboard and found the OT connections were on terminals 3 & 4 ffs.... I wonder if they have done the same with your boiler.
But to open up the casing to find out requires you to be Gas Safe registered if in the UK (how are they going to find out...).

**Comment by nyctomanica** [comment]
Had a nosey at the internal connections, and everything is annoyingly wired up exactly as the installation and service manual says it should be.

Thought I'd try reseating the connectors anyway, put it back together, and got exactly the same NO_CHANGE_TOO_LONG, NO_TRANSITION and ERROR_PROTOCOL errors as before.

I'm now really wondering if there's some kind of menu that the manual doesn't mention to enable OT, as a normal relay on/off stat works as expected...

Either way, I'm stumped at this point

**Comment by FreeBear-nc** [comment]
Measure the voltage between terminals 1 & 2 on the boiler. It should be between 18V and 24V. If you get nothing, remove the shorting link on terminals 3 & 4, and measure the voltage across those two.
Beyond that, I'm at a bit of a loss as to what to suggest. Your boiler appears to support OpenTherm, and the specification had been fully developed by the time your boiler was manufactured.

**Comment by nyctomanica** [comment]
There's 23v over 1 and 2, but no shorting link on 3 and 4!

I wonder if that's what's doing it!

**Comment by FreeBear-nc** [comment]
> There's 23v over 1 and 2, but no shorting link on 3 and 4!
> 
> I wonder if that's what's doing it!

Ah. terminals 3 & 4 should be for an external temperature sensor used for weather compensation. Do you have a fault code of 18 displayed ?
This would be "external sensor open circuit". Try putting a link in between terminals 3 & 4 although that might trigger a 10 fault code.
With no OpenTherm comms, you should also be getting a 5A error code displayed (if I'm reading the manual correctly)

**Comment by rhtenhove** [comment]
I've just setup my DIYLESS master shield with a `featheresp32` (an Adafruit Huzzah32 I had lying around).

It works partially, as in, I can control DHW, but not CH. Changing anything about CH doesn't show any response from the boiler. The sensors have worked a few times, showing water and return temperature, as well as relative modulation levels, but are stuck on Unknown now with my current setup. Tells me the boiler is good, it's either the shield or the software at fault.
My logs are filled mostly `NO_CHANGE_TOO_LONG` and sometimes `NO_TRANSITION`:

```
[13:25:54][D][opentherm:317]: Sending request with id 0 (STATUS)
[13:25:54][D][opentherm:318]: 00000000 00000000 00000000 00000000
type: READ_DATA; id: 0; HB: 0; LB: 0; uint_16: 0; float: 0.000000
[13:25:54][W][opentherm:353]: Protocol error occured while receiving response: type: NO_CHANGE_TOO_LONG; data: 00000000; clock: 1; capture: 00000000000000000000000111111111; bit_pos: 0
```

It's unclear to me what it's trying to do here, and what the failure message may indicate. Perhaps too slow of a response from the boiler, as in, unexpected response?

My method was hardly scientific, so no clear relation to a specific change I made so far.

I'll keep experimenting and keep track of what's happening after what change.

EDIT:

1. First I tried to use the develop branch, which had no effect other than to make the logs look cleaner.
2. Then I tried switching the pins. No effect.
3. Then I reversed the pins back to what they should be, and added a bunch of sensors again because, why not?

Now it works :-)

This is my current config:

```yaml
---
substitutions:
  slug: openthermmaster
  friendly_name: Opentherm Master
  dhw: Hot Water
  ch: CV

esphome:
  name: $slug

esp32:
  variant: esp32
  board: featheresp32

external_components:
  source: github://olegtarasov/esphome-opentherm@develop

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none
  use_address: 192.168.178.74

api:
ota:
  platform: esphome
captive_portal:

logger:
  level: DEBUG

opentherm:
  in_pin: 27
  out_pin: 33
  sync_mode: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP

sensor:
  - platform: wifi_signal
    name: $friendly_name WiFi RSSI
    filters:
      - or:
          - throttle: 60s
          - delta: 1.0
    accuracy_decimals: 0

  - platform: opentherm
    rel_mod_level:
      name: Boiler Relative modulation level
    t_boiler:
      name: Boiler Water temperature
    t_ret:
      name: Boiler Return water temperature
    t_dhw:
      name: $dhw Temperature
    t_exhaust:
      name: Boiler exhaust temperature
    ch_pressure:
      name: $ch Water Pressure
      accuracy_decimals: 1
    dhw_flow_rate:
      name: $dhw Flow Rate

  - platform: homeassistant
    id: living_temperature
    entity_id: sensor.temperature
    filters:
      # Push room temperature every second to update PID parameters
      - heartbeat: 1s

  - platform: homeassistant
    id: jungle_temperature
    entity_id: sensor.jungle_motion_sensor_temperature
    filters:
      - heartbeat: 1s

  - platform: homeassistant
    id: office_temperature
    entity_id: sensor.office_motion_sensor_temperature
    filters:
      - heartbeat: 1s

binary_sensor:
  - platform: opentherm
    ch_active:
      name: $ch active
    dhw_active:
      name: $dhw active
    flame_on:
      name: Flame on
    fault_indication:
      name: Fault indication
      entity_category: diagnostic
    diagnostic_indication:
      name: Diagnostic event
      entity_category: diagnostic
    service_request:
      name: Service Required
      entity_category: diagnostic
    low_water_pressure:
      name: Low Water Pressure
      entity_category: diagnostic
    flame_fault:
      name: Flame fault
      entity_category: diagnostic
    air_pressure_fault:
      name: Air Pressure fault
      entity_category: diagnostic
    water_over_temp:
      name: Water Over Temp
      entity_category: diagnostic

switch:
  - platform: opentherm
    ch_enable:
      name: Boiler $ch enabled
      restore_mode: RESTORE_DEFAULT_ON
    dhw_enable:
      name: $dhw Heating enabled
      restore_mode: RESTORE_DEFAULT_OFF

climate:
  - platform: pid
    id: living_heating_pid
    name: Living heating
    heat_output: t_set
    default_target_temperature: 20
    sensor: living_temperature
    visual:
      min_temperature: 15
      max_temperature: 25
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
    control_parameters:
      kp: 0.4
      ki: 0.004
      output_averaging_samples: 10

output:
  - platform: opentherm
    t_set:
      id: t_set
      min_value: 40
      max_value: 80
      zero_means_zero: true

button:
  - platform: restart
    name: Controller Restart

number:
  - platform: opentherm
    t_dhw_set:
      id: dhw_setpoint
      name: $friendly_name $dhw Setpoint
      min_value: 20
      max_value: 60
      mode: slider
      restore_value: true
      initial_value: 60
```

Logs are still riddled with the same error, but new messages have also appeared:

```
[13:55:03][D][opentherm:317]: Sending request with id 1 (CH_SETPOINT)
[13:55:03][D][opentherm:558]:    
[13:55:03][D][opentherm:562]: type: WRITE_DATA; id: 1; HB: 0; LB: 0; uint_16: 0; float: 0.000000
[13:55:03][D][opentherm:140]: Received OpenTherm response with id 1 (CH_SETPOINT)
[13:55:03][D][opentherm:558]:    
[13:55:03][D][opentherm:562]: type: WRITE_ACK; id: 1; HB: 0; LB: 0; uint_16: 0; float: 0.000000
[...]

```

My thinking now is the boiler expects certain values to be read, and won't behave if it isn't asked.

Now on to try adding more thermostats.

EDIT:

Well, it worked, once 😅 now back to many errors, no sensor values (some do appear after several minutes), and no response for CH, just DHW.

The errors keep coming even with the boiler unplugged, so my boiler just doesn't seem to respond to these messages. Perhaps it's expecting some message first, or a special order, or....

Restarting the boiler has no effect.

EDIT:

The next fix that appears to be working is moving to an `esp32s3` 😅 Not a single warning except for `Component opentherm took a long time for an operation (99 ms)` as I'm using `sync_mode: true`. Values were instantly available, CH responds as expected and instantly.

EDIT:

That turned out to be too soon, it's not stable, we're back to `NO_CHANGE_TOO_LONG` after a small change to the controller. A reboot of the boiler fixed it again. Quite unreliable :-(

Probably final edit:

I've learned about flux conductiveness today. After a thorough cleanse with IPA it now appears to function very stable and reliably. Now on to figure out how to best control it :-D
