### ISSUE TITLE
Does not work with GPIO41 as the output pin of esp32s3

### ISSUE THREAD

**Issue by ihormelnyk** [olegtarasov/esphome-opentherm#24]
Hi @olegtarasov 
I have such configuration:
```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

opentherm:
  in_pin: 7
  out_pin: 41
```
The output pin always has high logic level.

I've made some investigation of the opentherm hub.
It does not call out_pin_->setup() function, so the pin is not initialized properly.

Could you please fix this in the next version?
Thanks.

**Comment by olegtarasov** [comment]
Hi @ihormelnyk! I've added setup() calls in `develop` branch. You can reference it as an external component:

```yaml
external_components:
  source: github://olegtarasov/esphome-opentherm@develop
  refresh: 0s
```

Please let me know if it solves your issue.
