### ISSUE TITLE
Is it possible to implement a Number variable

### ISSUE THREAD

**Issue by Csikkovich** [olegtarasov/esphome-opentherm#29]
Currently when I create an opentherm number, I cannot change how the number should be displayed in the UI (currently only slider). It would be very helpful if it could be changed to box via the mode variable.

**Comment by FreeBear-nc** [comment]
Can you post your yaml.
Tried changing the number style from box to slider using mode, and it works for me.
```
number:
  - platform: opentherm
    max_t_set:
      name: "Boiler Max Setpoint"
      id: t_max_sp
      entity_category: config
      min_value: 20.0
      max_value: 75.0
      step: 0.1
      mode: "slider"
```
