### ISSUE TITLE
DHW not working on BAXI boiler

### ISSUE THREAD

**Issue by mool** [olegtarasov/esphome-opentherm#34]
I'm trying to migrate my ESPHome configuration from the https://github.com/ananyevgv/ESPHome-OpenTherm-Baxi_nuvola custom component to yours, but I'm having some issues making the DHW work.

I'm able to set the DHW temperature setpoint via the esphome device, I check the boiler display, and it has the configured value. But I see that the DHW temperature starts to drop slowly, and the boiler heats the water in the DHW tank. Any idea why that can be happening?

BTW, the central heating works great!

This is my configuration:

```yaml
substitutions:
  devicename: opentherm
  pid_temperature: sensor.sensor_cocina_temperature

esphome:
  name: $devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
logger:
api:

ota:
  platform: esphome

############################################
# OPENTHERM
############################################
opentherm:
  in_pin: 21
  out_pin: 22
  ch_enable: true
  dhw_enable: true

############################################
# SWITCH
############################################
switch:
  - platform: opentherm
    ch_enable:
      name: "${devicename} Central Heating enabled"
      id: ch_enabled
    dhw_enable:
      name: "${devicename} Domestic Hot Water enabled"
    otc_active:
      name: "${devicename} Outside Temperature Compensation active"
    ch2_active:
      name: "${devicename} Central Heating 2 active"
    summer_mode_active:
      name: "${devicename} Summer Mode active"
    dhw_block:
      name: "${devicename} Block DHW"

############################################
# NUMBER
############################################
number:
  - platform: opentherm
    # t_set - This is set as an output
    # t_set_ch2 - Disabled, not used
    t_dhw_set:
      id: dhw_setpoint
      name: "${devicename} Hot water setpoint"
      initial_value: 50
      max_value: 80.0
      min_value: 30.0
      restore_value: true
      step: 1
    max_t_set:
      name: "${devicename} Maximum allowable CH water setpoint"
      max_value: 85.0
      min_value: 25.0
      restore_value: true
      step: 1
    max_rel_mod_level:
      name: Maximum relative modulation level
      max_value: 100.0
      min_value: 0.0
      restore_value: true
      step: 1
    otc_hc_ratio:
      name: "${devicename} OTC heat curve ratio"
      max_value: 100.0
      min_value: 0.0
      restore_value: true
      step: 1

############################################
# BINARY SENSOR
############################################
binary_sensor:
  - platform: opentherm
    fault_indication:
      name: "${devicename} Fault"
      entity_category: diagnostic
    ch_active:
      name: "${devicename} Central Heating active"
    ch2_active:
      name: "${devicename} Central Heating 2 active"
    cooling_active:
      name: "${devicename} Cooling active"
    dhw_active:
      name: "${devicename} Domestic Hot Water active"
    dhw_present:
      name: "${devicename} DHW present"
    dhw_storage_tank:
      name: "${devicename} DHW storage tank"
    flame_on:
      name: "${devicename} Flame on"
      id: flame
    diagnostic_indication:
      name: "${devicename} Diagnostic"
      entity_category: diagnostic
    control_type_on_off:
      name: "${devicename} Control type is on/off"
    cooling_supported:
      name: "${devicename} Cooling supported"
    controller_pump_control_allowed:
      name: "${devicename} Controller pump control allowed"
    ch2_present:
      name: "${devicename} CH2 present"
    dhw_setpoint_transfer_enabled:
      name: "${devicename} Remote boiler parameters: DHW setpoint transfer enabled"
    max_ch_setpoint_transfer_enabled:
      name: "${devicename} Remote boiler parameters: CH maximum setpoint transfer enabled"
    dhw_setpoint_rw:
      name: "${devicename} Remote boiler parameters: DHW setpoint read/write"
    max_ch_setpoint_rw:
      name: "${devicename} Remote boiler parameters: CH maximum setpoint read/write"
    service_request:
      name: "${devicename} Service required"
    lockout_reset:
      name: "${devicename} Lockout Reset"
    low_water_pressure:
      name: "${devicename} Low water pressure fault"
    flame_fault:
      name: "${devicename} Flame fault"
    air_pressure_fault:
      name: "${devicename} Air pressure fault"
    water_over_temp:
      name: "${devicename} Water overtemperature"

############################################
# SENSOR
############################################
sensor:
  - platform: opentherm
    rel_mod_level:
      name: "${devicename} Relative modulation level"
      id: modulation
    ch_pressure:
      name: "${devicename} Water pressure in CH circuit"
    dhw_flow_rate:
      name: "${devicename} Water flow rate in DHW circuit"
    t_boiler:
      id: t_boiler
      name: "${devicename} Boiler water temperature"
    t_dhw:
      id: t_dhw
      name: "${devicename} DHW temperature"
    t_outside:
      name: "${devicename} Outside temperature"
    t_ret:
      id: t_ret
      name: "${devicename} Return temperature"
    t_flow_ch2:
      name: "${devicename} Flow water temperature CH2 circuit"
    t_dhw2:
      name: "${devicename} Domestic hot water temperature 2"
    t_exhaust:
      name: "${devicename} Exhaust temperature"
    t_dhw_set_ub:
      name: "${devicename} Upper bound for adjustment of DHW setpoint"
    t_dhw_set_lb:
      name: "${devicename} Lower bound for adjustment of DHW setpoint"
    max_t_set_ub:
      name: "${devicename} Upper bound for adjustment of max CH setpoint"
    max_t_set_lb:
      name: "${devicename} Lower bound for adjustment of max CH setpoint"
    t_dhw_set:
      name: "${devicename} Domestic hot water temperature setpoint"
    max_t_set:
      name: "${devicename} Maximum allowable CH water setpoint"
    oem_fault_code:
      name: "${devicename} OEM fault code"
      id: oem_error
    oem_diagnostic_code:
      name: "${devicename} OEM diagnostic code"
    opentherm_version_device:
      name: "${devicename} Version of OpenTherm implemented by slave"
    device_type:
      name: "${devicename} Slave product type"
    device_version:
      name: "${devicename} Slave product version"
    device_id:
      name: "${devicename} Slave ID code"

  - platform: homeassistant
    id: ch_pid_temperature
    entity_id: $pid_temperature
    filters:
      - heartbeat: 1s

############################################
# TEXT SENSOR
############################################
text_sensor:
  - platform: template
    name: "${devicename} Boiler error"
    icon: mdi:water-boiler-alert
    lambda: |-
      uint8_t var = (id(oem_error).state);
      switch (var) {
        case 0: return std::string("");
        case 1: return std::string("E01 No ignition");
        case 2: return std::string("E02 Overheat protection thermostat activated");
        case 3: return std::string("E03 Draft protection sensor activated");
        case 4: return std::string("E04 Frequent flame failure");
        case 5: return std::string("E05 Heating sensor malfunction");
        case 6: return std::string("E06 Domestic hot water circuit sensor malfunction");
        case 10: return std::string("E10 Water pressure sensor malfunction");
        case 11: return std::string("E11 External programmable temperature sensor input opening malfunction (= 04)");
        case 12: return std::string("E12 No permission from the differential hydraulic pressure sensor (pressure switch)");
        case 13: return std::string("E13 Sticking contacts of the differential hydraulic pressure switch");
        case 18: return std::string("E18 System filling enabled (note)");
        case 19: return std::string("E19 System filling malfunction");
        case 25: return std::string("E25 Air in the system");
        case 35: return std::string("E35 Parasitic flame (flame error)");
        case 80 ... 96: return std::string("E80-96 Removable panel error)");
        case 97: return std::string("E97 Incorrect mains frequency)");
        case 98: return std::string("E98 Gas valve relay contact problem, internal error");
        case 99: return std::string("E99 Relay contact problem, internal error");
        default: return std::string("Unknown error");
      }

############################################
# OUTPUT
############################################
output:
  - platform: opentherm
    t_set:
      id: t_set
      min_value: 35
      max_value: 45
      zero_means_zero: true

############################################
# CLIMATE
############################################
climate:
  - platform: pid
    name: "Central Heating"
    id: pid_climate
    heat_output: t_set
    default_target_temperature: 24
    sensor: ch_pid_temperature
    visual:
      min_temperature: 20
      max_temperature: 30
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
    control_parameters:
      kp: 0.4
      ki: 0.004

############################################
# BUTTON
############################################
button:
  - platform: template
    name: "${devicename} PID autotune"
    on_press:
      - climate.pid.autotune: pid_climate
```
